/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_cpp_AppActivity */

#ifndef _Included_org_cocos2dx_cpp_AppActivity
#define _Included_org_cocos2dx_cpp_AppActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_cpp_AppActivity
 * Method:    on_login_finish
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_cocos2dx_cpp_AppActivity_on_1login_1finish
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
